package com.telegram.videoplayer.downloader.utils;

import android.content.Context;
import android.content.SharedPreferences;

import org.apache.commons.lang3.time.DateUtils;

import javax.inject.Inject;
import javax.inject.Singleton;

@SuppressWarnings({"FieldCanBeLocal", "FinalPrivateMethod", "unchecked", "rawtypes", "SameReturnValue"})
@Singleton

public final class Utils {
    public final String prefname = "EASYMONEY";
    private final String AFFILATEBAL;
    private final String AFFILATEDBONUSINDEX;
    private final String ANBANNERID;
    private final String ANINTERSTITALID;
    private final String ANNATIVEDID;
    private final String BANNER;
    private final String BANNERDATAURL_STARTSCEEN;
    private final String BASEAPI;
    private final String BASEDOMAIN;
    private final String CHECKPACKAGENAME;
    private final String CONTACTLISTINFO;
    private final String DIMNDHISTORYINFO;
    private final String DISPLAYAD;
    private final String EMAILHELP;
    private final String ERMKEYWORD;
    private final String ERMLANGUAGE;
    private final String ERMLU;
    private final String FBADID;
    private final String FBADIDGAME;
    private final String FBADIDLOADMORE;
    private final String FBBANNERADID;
    private final String FBNADID;
    private final String FBNADIDSINGLE;
    private final String FBNADIDSTATUSW;
    private final String FBREWARDMITRON;
    private final String FESTIVALTEXT;
    private final String FESTIVALWEBPAGEURL;
    private final String FREERNIGINFO;
    private final String GOOGLEBANNERARTICLE;
    private final String GOOGLEBANNERMITRON_PLAYER;
    private final String GOOGLEINTERSTITIALARTICLE;
    private final String GOOGLEINTERSTITIALMITRON_TAGDETAILS;
    private final String GOOGLEINTERSTITIALMITRON_USERDETAILS;
    private final String GOOGLENATIVEARTICLE;
    private final String GOOGLENATIVEMITRON_PLAYER;
    private final String HOMEBANNER;
    private final String HOMEBANNERREDIRECT;
    private final String INTERVAL;
    private final String INVITEBONUSINDEX;
    private final String ISADEVERYTIMESTART;
    private final String ISAFFBNSSHOW;
    private final String ISBNRCLK;
    private final String ISFULLCLK;
    private final String ISINVBNSSHOW;
    private final String ISLANGUAGESELECTABLE;
    private final String ISNATVCLK;
    private final String ISNEWSTICKER;
    private final String ISOPNCLK;
    private final String ISPKGNAMEID;
    private final String ISRWDCLK;
    private final String ISSIGNBNSSHOW;
    private final String ISSIGNUPBONUSDONE;
    private final String IS_PHONE_NUMBER;
    private final String KEY;
    private final String LANGUAGEARRAY;
    private final String LANGUAGESELECTIONDONE;
    private final String LASTSPEEDTIME;
    private final String LASTTIMING;
    private final String MAINBAL;
    private final String NADID;
    private final String NETWORKSPEED;
    private final String NOTIFICATIONINDEXUPDATEDASHBOARD;
    private final String OPENAD;
    private final String OPTIONAL_VERSION;
    private final String OPTIONAL_VERSIONMESSAGE;
    private final String PACKAGEFORSTICKER;
    private final String PHONE_NUMBER;
    private final String PKGNAME;
    private final String PRIMARY_COLOR;
    private final String RANDOMERM;
    private final String RANDOMOTHER;
    private final String RDMBAL;
    private final String REDIRECTURL_STARTSCREEN;
    private final String RFRLBAL;
    private final String RFRLCODE;
    private final String RFRLPLANLINK;
    private final String RFRLSHARELINK;
    private final String RID;
    private final String SELFVIEWBAL;
    private final String SESSIONID;
    private final String SETWEBVIEWORNOT;
    private final String SHARINGURL;
    private final String SHOWADATDOWNLOAD;
    private final String SHOWCP;
    private final String SHOWEXITSCREEN;
    private final String SHOWFESTIVALPAGE;
    private final String SKKIPPEDCONTACT;
    private final String SSL;
    private final String SSLURL;
    private final String TERMSANDCONDITION;
    private final String THEMESELECTIONDONE;
    private final String THEME_SELECTED;
    private final String THEME_SELECTED_ID;
    private final String UPLOADCREATEVIEWBAL;
    private final String UPLOADTERMSANDCONDITION;
    private final String USEROVERRIDE;
    private final String USERUPLOADINFO;
    private final String UVID;
    private final String WHATSAPPHELP;
    private final String WHICHADFIRST;
    private final SharedPreferences.Editor editor;
    private final Context mcontext;
    private final long fixtime = DateUtils.MILLIS_PER_DAY;
    private final long fixtime60 = 60000;
    private final long intervalTIme = 1200000;
    private final SharedPreferences sharedPref;

    @Inject
    public Utils(Context context) {
        this.mcontext = context;
        SharedPreferences sharedPreferences = context.getSharedPreferences(this.prefname, 0);
        this.sharedPref = sharedPreferences;
        this.editor = sharedPreferences.edit();
        this.BANNER = "banner";
        this.GOOGLEBANNERMITRON_PLAYER = "googleBannerMitron_player";
        this.FBBANNERADID = "fbbanneradId";
        this.KEY = "key";
        this.OPENAD = "openad";
        this.GOOGLEINTERSTITIALMITRON_TAGDETAILS = "googleInterstitialMitron_tagdetails";
        this.GOOGLEINTERSTITIALMITRON_USERDETAILS = "googleInterstitialMitron_userdetails";
        this.RID = "rid";
        this.UVID = "uvid";
        this.NADID = "nadId";
        this.GOOGLENATIVEMITRON_PLAYER = "googleNativeMitron_player";
        this.FBADID = "fbadId";
        this.FBADIDGAME = "fbadIdGame";
        this.FBADIDLOADMORE = "fbadIdLoadMore";
        this.FBNADID = "fbnadId";
        this.FBNADIDSTATUSW = "fbnadIdStatusW";
        this.FBNADIDSINGLE = "fbnadIdSingle";
        this.FBREWARDMITRON = "fbRewardMitron";
        this.SHOWADATDOWNLOAD = "ShowAdAtDownload";
        this.GOOGLEBANNERARTICLE = "googleBannerArticle";
        this.GOOGLEINTERSTITIALARTICLE = "googleInterstitialArticle";
        this.GOOGLENATIVEARTICLE = "googleNativeArticle";
        this.ANNATIVEDID = "anNativedId";
        this.ANBANNERID = "anBannerId";
        this.ANINTERSTITALID = "anInterStitalId";
        this.INTERVAL = "interval";
        this.DISPLAYAD = "displayAd";
        this.WHICHADFIRST = "whichAdFirst";
        this.SETWEBVIEWORNOT = "setWebViewOrNot";
        this.ISLANGUAGESELECTABLE = "isLanguageSelectable";
        this.LANGUAGESELECTIONDONE = "languageSelectionDone";
        this.LANGUAGEARRAY = "languageArray";
        this.UPLOADTERMSANDCONDITION = "uploadTermsAndCondition";
        this.TERMSANDCONDITION = "TermsAndCondition";
        this.BASEDOMAIN = "baseDomain";
        this.BASEAPI = "baseAPI";
        this.FESTIVALTEXT = "Festivaltext";
        this.FESTIVALWEBPAGEURL = "festivalWebPageUrl";
        this.SHOWFESTIVALPAGE = "showFestivalPage";
        this.OPTIONAL_VERSIONMESSAGE = "optional_versionMessage";
        this.OPTIONAL_VERSION = "optional_version";
        this.ISNEWSTICKER = "isNewSticker";
        this.PACKAGEFORSTICKER = "packageforsticker";
        this.SHARINGURL = "sharingurl";
        this.HOMEBANNER = "homebanner";
        this.HOMEBANNERREDIRECT = "homebannerredirect";
        this.BANNERDATAURL_STARTSCEEN = "bannerDataURL_startsceen";
        this.REDIRECTURL_STARTSCREEN = "RedirectURL_startscreen";
        this.SHOWEXITSCREEN = "showExitScreen";
        this.PHONE_NUMBER = "phoneNumber";
        this.IS_PHONE_NUMBER = "isPhoneNumber";
        this.SESSIONID = "sessionId";
        this.AFFILATEBAL = "AFFILATEBAL";
        this.SELFVIEWBAL = "myVideoViewBal";
        this.UPLOADCREATEVIEWBAL = "uploadCreateViewBal";
        this.MAINBAL = "mainBal";
        this.RDMBAL = "rdmBal";
        this.FREERNIGINFO = "freErnngInfo";
        this.CONTACTLISTINFO = "contactListInfo";
        this.DIMNDHISTORYINFO = "dmndHistoryInfo";
        this.USERUPLOADINFO = "userUploadInfo";
        this.NOTIFICATIONINDEXUPDATEDASHBOARD = "NotificationIndexUpdateDashboard";
        this.ERMKEYWORD = "ermKeyWord";
        this.ERMLU = "ermLOUN";
        this.ERMLANGUAGE = "ermLanguage";
        this.WHATSAPPHELP = "wtsapHelp";
        this.EMAILHELP = "emailHelp";
        this.SKKIPPEDCONTACT = "skkippedcontact";
        this.SHOWCP = "showcp";
        this.PRIMARY_COLOR = "primary_color";
        this.THEME_SELECTED = "theme_selected";
        this.THEME_SELECTED_ID = "theme_selected_id";
        this.THEMESELECTIONDONE = "themeselectiondone";
        this.RANDOMERM = "randomErm";
        this.RANDOMOTHER = "randomOther";
        this.ISADEVERYTIMESTART = "isAdEveryTimeStart";
        this.ISAFFBNSSHOW = "isAffBnsShow";
        this.ISINVBNSSHOW = "isInvBnsShow";
        this.ISSIGNBNSSHOW = "isSignBnsShow";
        this.INVITEBONUSINDEX = "inviteBonusIndex";
        this.ISSIGNUPBONUSDONE = "isSignUPBonusDone";
        this.AFFILATEDBONUSINDEX = "affilatedBonusIndex";
        this.NETWORKSPEED = "networkSpeed";
        this.LASTSPEEDTIME = "lastSpeedTime";
        this.USEROVERRIDE = "userOverride";
        this.CHECKPACKAGENAME = "checkPackageName";
        this.ISPKGNAMEID = "isPkgNameId ";
        this.ISFULLCLK = "isFullClk";
        this.ISBNRCLK = "isBnrClk";
        this.ISNATVCLK = "isNatvClk";
        this.ISOPNCLK = "isOpnClk";
        this.ISRWDCLK = "isRwdClk";
        this.LASTTIMING = "lastTiming";
        this.PKGNAME = "PKgName";
        this.RFRLCODE = "RFRLCODE";
        this.RFRLPLANLINK = "RFRLPLANLINK";
        this.RFRLSHARELINK = "RFRLSHARELINK";
        this.SSL = "SSLSHA";
        this.SSLURL = "SSLURL";
        this.RFRLBAL = "rfrlBal";
    }
}
